export const GeneralTypes = {
    SET_LOADING: "SET_LOADING",
    SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
    GET_ALL_BRANDS: "GET_ALL_BRANDS",
    GET_MORE_BRANDS: "GET_MORE_BRANDS",
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    GET_TOP_CATEGORIES: "GET_TOP_CATEGORIES",
    GET_MORE_CATEGORIES: "GET_MORE_CATEGORIES",
    REFRESH_DASHBOARD: "REFRESH_DASHBOARD"
}
