export const ProductTypes = {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_WISHLIST: "GET_WISHLIST",
    ADD_PRODUCT_WISHLIST: "ADD_PRODUCT_WISHLIST",
    REMOVE_PRODUCT_WISHLIST: "REMOVE_PRODUCT_WISHLIST"
}
