export const ProductTypes = {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_MORE_ALL_PRODUCTS: "GET_MORE_ALL_PRODUCTS",
    RESET_ALL_PRODUCTS:"RESET_ALL_PRODUCTS",
    GET_WISHLIST: "GET_WISHLIST",
    GET_MORE_WISHLIST: "GET_MORE_WISHLIST",
    RESET_GET_WISHLIST: "RESET_GET_WISHLIST",
    ADD_PRODUCT_WISHLIST: "ADD_PRODUCT_WISHLIST",
    REMOVE_PRODUCT_WISHLIST: "REMOVE_PRODUCT_WISHLIST",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    GET_ORDERS:"GET_ORDERS",
    GET_MORE_ORDERS:"GET_MORE_ORDERS",
    EMPTY_CART:"EMPTY_CART"
}
